- name: installing a tomcat
  hosts: all
  become: true
  tasks:
    - name: install java
      yum:
        name: java
        state: latest

    - name: download tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.73/bin/apache-tomcat-8.5.73.tar.gz
        dest: /root/webapp

    - name: extract packages
      unarchive:
        src: /root/webapp/apache-tomcat-8.5.73.tar.gz
        dest: /root/webapp/
        remote_src: yes

    - name: start tomcat services
      shell: nohup /root/webapp/apache-tomcat-8.5.73/bin/startup.sh
